<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="454.673" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2023-03-29T19:13:18" tests="0" file="cypress/e2e/cards/withdrawFromCard.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Withdraw from card" timestamp="2023-03-29T19:13:18" tests="2" time="454.666" failures="2">
    <testcase name="Withdraw from card Test that the user is able to access withdraw from physical card" time="96.503" classname="Test that the user is able to access withdraw from physical card">
      <failure message="Timed out retrying after 80000ms: Expected to find content: &apos;Damilare&apos; within the element: &lt;h1.title&gt; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 80000ms: Expected to find content: 'Damilare' within the element: <h1.title> but never did.
    at Context.eval (webpack:///./cypress/e2e/cards/withdrawFromCard.cy.js:19:46)]]></failure>
    </testcase>
    <testcase name="Withdraw from card &quot;before each&quot; hook for &quot;Test that the user is able to access withdraw from virtual card&quot;" time="30.268" classname="&quot;before each&quot; hook for &quot;Test that the user is able to access withdraw from virtual card&quot;">
      <failure message="`cy.visit()` failed trying to load:

https://devcardholder.essolo.com/onboarding/signin

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: ESOCKETTIMEDOUT

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Withdraw from card`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

https://devcardholder.essolo.com/onboarding/signin

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: ESOCKETTIMEDOUT

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Withdraw from card`
    at <unknown> (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:138252:82)
    at visitFailedByErr (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:137644:12)
    at <unknown> (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:138251:11)
    at tryCatcher (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:8914:23)
    at Promise._settlePromiseFromHandler (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:6849:31)
    at Promise._settlePromise (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:6906:18)
    at Promise._settlePromise0 (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:6951:10)
    at Promise._settlePromises (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:7027:18)
    at _drainQueueStep (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:3621:12)
    at _drainQueue (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:3614:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:3630:5)
    at Async.drainQueues (https://devcardholder.essolo.com/__cypress/runner/cypress_runner.js:3500:14)
From Your Spec Code:
    at LoginPage.accessLoginModal (webpack:///./cypress/support/pages/shared/login-page.js:11:7)
    at Context.eval (webpack:///./cypress/e2e/cards/withdrawFromCard.cy.js:12:16)

From Node.js Internals:
  Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (<embedded>:1955:73317)
      at Object.onceWrapper (node:events:641:28)
      at ClientRequest.emit (node:events:527:28)
      at TLSSocket.emitRequestTimeout (node:_http_client:771:9)
      at Object.onceWrapper (node:events:641:28)
      at TLSSocket.emit (node:events:539:35)
      at Socket._onTimeout (node:net:516:8)
      at listOnTimeout (node:internal/timers:559:17)
      at process.processTimers (node:internal/timers:502:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>